<a href="https://colab.research.google.com/github/fayzullaevfarrukh98/ai_foundation/blob/master/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [4]:
print(pd.__version__)

2.2.2

In [20]:
df.head(6) # default 5 rows

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4     Audi       1
5  Hyundai       4

In [21]:
df.tail(-1 ) # default 5 rows

      cars  counts
1    Volvo       7
2     Ford       2
3    Tesla       5
4     Audi       1
5  Hyundai       4

In [22]:
df.shape

(6, 2)

In [24]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [26]:
df.dtypes

cars      object
counts     int64
dtype: object

In [29]:
df.describe() #numerical columns only

         counts
count  6.000000
mean   3.666667
std    2.160247
min    1.000000
25%    2.250000
50%    3.500000
75%    4.750000
max    7.000000

In [41]:
df.iloc[0:]

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4     Audi       1
5  Hyundai       4

In [10]:
mydataset = {
    'cars':["BMW","Volvo","Ford","Tesla", "Audi", "Hyundai" ],
    'counts':[3, 7, 2, 5, 1, 4]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       5
4     Audi       1
5  Hyundai       4

In [47]:
df.loc[1:3,"cars", ]

1    Volvo
2     Ford
3    Tesla
Name: cars, dtype: object

In [52]:
df[df["counts"] >5]

    cars  counts
1  Volvo       7

In [54]:
# df.mean(numeric_only=True)
df["counts"].mean()

np.float64(3.6666666666666665)

In [53]:
df.sum()

cars      BMWVolvoFordTeslaAudiHyundai
counts                              22
dtype: object

In [55]:
df.min()

cars      Audi
counts       1
dtype: object

In [57]:
df.max()

cars      Volvo
counts        7
dtype: object

In [58]:
df.median(numeric_only=True)

counts    3.5
dtype: float64

In [59]:
df.count()

cars      6
counts    6
dtype: int64

In [60]:
df.std(numeric_only=True)

counts    2.160247
dtype: float64

In [65]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [71]:
df_missing.dropna(how="all")

    cars  counts
0    BMW     3.0
1  Volvo     7.0
3   None     5.0
4   Audi     NaN
5   None     4.0

In [69]:
data_with_missing = {
    "cars":["BMW","Volvo",None,None, "Audi", None ],
    "counts":[3, 7, None, 5, None, 4]
}
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

    cars  counts
0    BMW     3.0
1  Volvo     7.0
2   None     NaN
3   None     5.0
4   Audi     NaN
5   None     4.0

In [73]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3  unknown     5.0
4     Audi     0.0
5  unknown     4.0

In [79]:
df = pd.read_csv("Titanic-Dataset.csv")

df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [81]:
df.to_excel("test.xlsx")

In [82]:
df = pd.read_excel("test.xlsx")
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [83]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [84]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, None, 'Audi', None]